### ISSUE TITLE
I added astOS to neofetch.

### ISSUE THREAD

**Issue by Elecleus** [CuBeRJAN/astOS#17]
I have just added astOS to neofetch.
It is waiting to be merged now.
You can view it now at [https://github.com/dylanaraps/neofetch/pull/2184](url).
And you can try it by cloning my repository at [https://github.com/Elecleus/neofetch](url), and then
```shell
sh ./neofetch --ascii_distro astOS
```

**Comment by CuBeRJAN** [comment]
great, thank you!
