### ISSUE TITLE
Support EndeavourOS

### ISSUE THREAD

**Issue by MaluNoPeleke** [CuBeRJAN/astOS#23]
Can you add support for [EndeavourOS](https://endeavouros.com/)?

**Comment by i2** [comment]
@MaluNoPeleke I just added EOS support. You can download it [here](https://github.com/ashos/ashos). Feel free to follow us on [Discord](https://discord.gg/YVHEC6XNZw) as I will post a demo video soon!

**Comment by MaluNoPeleke** [comment]
Thanks a lot!
