### ISSUE TITLE
Swapfile??

### ISSUE THREAD

**Issue by karmakarmeghdip** [CuBeRJAN/astOS#30]
How do I get swapfile working in an astOS installation?

**Comment by CuBeRJAN** [comment]
You should be able to chroot into the snapshot, then follow the steps outlined by the Arch wiki (https://wiki.archlinux.org/title/Btrfs#Swap_file).

Personally I recommend using ZRAM instead (https://wiki.archlinux.org/title/Zram).

**Comment by karmakarmeghdip** [comment]
> You should be able to chroot into the snapshot, then follow the steps outlined by the Arch wiki (https://wiki.archlinux.org/title/Btrfs#Swap_file).

That didn't work, I tried that.... Only the fstab change persisted. Systemd gives me error now when I try to boot my system up

> Personally I recommend using ZRAM instead (https://wiki.archlinux.org/title/Zram).

I have just 4GB of RAM so ZRAM is pretty useless for me.....

**Comment by CuBeRJAN** [comment]
I have been able to create a swapfile based on the ArchWiki information with a few extra steps. 

First mount the system partition like so (do everything as root):
```bash
mount /dev/*** /mnt -o subvolid=0
```

Then you can make the subvolume
```bash
btrfs sub create /mnt/\@swap
```

Then finally create the swapfile
```bash
btrfs fi mkswapfile --size 4g --uuid clear /mnt/\@swap/swapfile
```

At this point you can chroot inside the snapshot, we'll continue from there.
```bash
ast chroot <snapshot>
```

Make the swap path
```
mkdir /swap
```

There open up ``/etc/fstab`` and add 2 new entries.
```
UUID="xxx" /swap btrfs subvol=@swap,noatime 0 0 # Here use system partition UUID
/swap/swapfile none swap defaults 0 0
```

Now you can exit the chroot
```
exit 0
```

and deploy.
```
ast deploy <snapshot>
```

I think this process could be automated in some way or a part of the installer, or at least it deserves a section in the docs - I'll look at that later.

**Comment by karmakarmeghdip** [comment]
Hmm, I figured out a solution to swapfile just a while ago but did it a little differently...

I created a btrfs subvolume using
`btrfs subvolume create /var/swap`

and then created a swapfile using
`btrfs filesystem mkswapfile --size 4g --uuid clear /var/swap/swapfile`

and `swapon /var/swap/swapfile`

also updated fstab from within chroot and exited and deployed the snapshot...
I could make a PR to update the README.md too...

But I am having a lot of other issues like stuff don't make sense to me...
Is `ast sync <tree>` supposed to update all the packages installed from repos and aur in all the branches, since it wasn't quite doing that for me, if so then what is tree-upgrade for?? Also why was it giving file already exists error for me when I tried to upgrade... also when I upgrade do I need to upgrade for each and every child snapshot, like rebuilding hyprland-git 3 times for 3 children nodes or fetching the same package multiple times?? Also kernel updates were working when I tried to sync... I have a lot of questions about this project and maybe the README can be improved with all the necessary info and better description if you clarify my confusions...
