### ISSUE TITLE
Suggestion: make use of archinstall

### ISSUE THREAD

**Issue by i2** [CuBeRJAN/astOS#4]
Would it be possible to make use of the official [archinstall](https://github.com/archlinux/archinstall) to conduct the installation process of ast? This would make ast concept even more modular. It would delegate the task of installation to archinstall which is getting more and more streamlined and hence would just focus on ast itself.
Right now, 3 arguments /dev/btrfs-partition /dev/sda and /dev/efi-partition are used.

Thanks!

**Comment by CuBeRJAN** [comment]
The installer will likely be rewritten in the (near) future, so it's certainly a possibility for archinstall to be used.
